### PR TITLE
#11 - Register Tile With Custom Display

### LINKED ISSUE #11: Register Tile with custom display
Instead of corresponds to user if check.
https://github.com/DiscipleTools/disciple-tools-survey-collection/blob/9a1175ac119b93dcbe320a62e3f369d9943a724d/tile/custom-tile.php#L42

### LINKED ISSUE #29: hardcode new metrics in the dashboard tile
order and metrics the same as the data collected in the reports form

they want the metrics in the dashboard tile to reflect the metrics order and total from the form.

The new fields in the reports form are

with the same name in lower case as the name of the field in the image

Image

They wouldn't need the accountability date to be in the metrics for Sunday, but a future issue/feature request, would be to have a count of days since the last accountability date, in the list of metrics see #31 unless it's easy to roll that metric into this issue

### PR DESCRIPTION
**Pull request by kodinkat**
Report tiles are now registered by default, enabling visibility to be managed via custom display conditions within admin custom tiles section.

- fixes #11 
- fixes #29

### CODE REVIEW

**Comment by squigglybob** [comment]
For some reason the dashboard total participants isn't picking up one of the reports
image

image

**Comment by kodinkat** [comment]
Did not mean to force!! :( Sorry...

**Comment by squigglybob** [comment]
no worries bro 😆

**Comment by squigglybob** [comment]
It all squash merged in fine, so no harm done.
It would be interesting to know why it wouldn't let you normal push it...
I imagine it was probably because of a thing about the branches having differing commits or something.

I've never had much luck with rebasing myself, it always seems quite complicated and messy.
I generally just stick with (from memory :o/ )

`git fetch upstream`
`git merge upstream/master`

to get the latest master changes into my branches

**Pull request merged**
